services:
  - type: web
    name: astra6bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OANDA_API_KEY
        sync: false
      - key: OANDA_ACCOUNT_ID
        sync: false
      - key: OANDA_ENVIRONMENT
        value: practice
